name: Phase1 CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn faiss-cpu sentence-transformers numpy

      - name: Lint and Compile
        run: |
          python -m compileall phase1_pilot/app
          echo "Syntax OK"

      - name: Report
        run: echo "Phase 1 CI/CD completed successfully."
