apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot-phase2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
        - name: router-service
          image: chatbot/router:latest
          envFrom:
            - secretRef:
                name: chatbot-secrets
          ports:
            - containerPort: 8000
