apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-phase3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jameswniu/multi-intent-ai-chatbot-assistant'
    targetRevision: HEAD
    path: phase3_scaling/helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
