global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'chatbot-phase3'
    metrics_path: /metrics
    static_configs:
      - targets: ['router-service:8000']
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
