apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-phase3
  labels:
    app: multi-intent-ai-chatbot
spec:
  replicas: 4
  selector:
    matchLabels:
      app: multi-intent-ai-chatbot
  template:
    metadata:
      labels:
        app: multi-intent-ai-chatbot
    spec:
      containers:
        - name: router-service
          image: jameswniu/chatbot-router:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "production"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: OPENAI_API_KEY
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
