name: Phase2 Multi-Stage Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t chatbot/router -f phase2_production/Dockerfile .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Unit Tests
        run: python -m compileall phase2_production/services

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Kubernetes
        run: kubectl apply -f phase2_production/helm/deployment.yaml
